Second and third section
hyper-island-exploring-code-project/doraemon pull request #13
Opened 2024-05-30 17:53 UTC by vsafonova

-Created layout for the second and third sections, 
-add the image with the cat with pancakes,
-change the Chinese text in the second section into Japanese (Just translated English text into Japanese),
-delete fonts import

2024-05-30 18:40 UTC, elen-oz requested changes

2024-05-30 18:40 UTC, elen-oz commented on src/styles.css
> +  display: flex;
here

2024-05-30 18:40 UTC, elen-oz commented on src/styles.css
> +  width: 35%;
here

2024-05-30 18:40 UTC, elen-oz commented on src/styles.css
> +  color: #b8b2b2;
here

2024-05-30 18:40 UTC, elen-oz commented on src/styles.css
>    background-color: #ff6636;
here

2024-05-30 18:40 UTC, elen-oz commented on src/styles.css
> +.bg_orange img {
here

2024-05-30 19:20 UTC, Quantinx commented on src/styles.css
> +  display: flex;
This may cause issues for me, will check

2024-05-31 08:32 UTC, Quantinx approved these changes
Have compensated for the changes in my own classes

2024-05-31 08:34 UTC, elen-oz approved these changes

2024-05-31 08:34 UTC, merged